### ISSUE TITLE
Shouldn't the coefficients of sparse CCA be small?

### ISSUE THREAD

**Issue by fabioboh** [Teekuningas/pypma#1]
First of all, thanks a lot for sharing this code! I was running your example (plot_cca.ipynb) and I find some of the outputs a bit puzzling. One of my concerns is that the weights do not change when one introduces the penalties (i.e. penaltyu/v is set to 0.9 from 1). They stay exactly the same, even when one sets penaltyu/v to 0.8. Furthermore, when the penalty for v is set to 0.7 or smaller, the weights become nans or inf. Why is that? Finally, it seems to me that the weights are not sparse, as there are many large negative weights, particularly for Z: -0.319, -12.652, -14.360, -10.534, 1.000.

If my interpretation is correct, you are implementing Algorithm 3 from the original publication (doi: 10.1093/biostatistics/kxp008) for the determination of the weights. Then it should hold, in your example:

sum_i abs(weight_i) <=  penalty_v*sqrt(5)

This is not the case. Do you agree? If not, what is wrong in my interpretation?

Thanks in advance for your attention!

**Comment by teekuningas** [comment]
Hello!

Yes, I agree that the correlation coefficient should be lower when penalized. I think the problem lies in the toy example which is too simple to demonstrate the effect of penalization. I updated the example to have a more real life -like example: https://teekuningas.github.io/sparsecca/auto_examples/plot_cca.html

The nans and infs were result of the weight printing function which tried to "normalize" the weights when printed for easy comparison between methods. That is fixed now. 

The PMD algorithm however is intact and should work fine. When writing it, I tested it against the original matlab implementation of the authors with their data and at least for the test runs they seemed to produce the same results.

Glad that you are interested!

-- Erkka

**Comment by teekuningas** [comment]
And, as said, the weights are normalized for printing. You can take the normalization off if you want to compare the weights to penalties on absolute scale. Even without that, however, it should now be visibly clear that the weights get more sparse with penalties.

**Comment by fabioboh** [comment]
Hello Erkka!

Thanks a lot for your answer. Before applying it to your artificially generated data, I applied it to "real world" data, and also noticed that:

1- coefficients do not get small by introducing penalties
2- coefficients differ compared to the ones produced by the R implementation (I used the rpy2 package to use it).

I find the example you produced now too simple, as it has only two components (a scenario that hardly correspond to the typical use). On the other hand, I liked the one you had before, and since the sCCA is just algebra, I think it should work both on artificial and real world data. Let me see whether I manage to create a self-contained example...

**Comment by teekuningas** [comment]
Hi! I think it is the printing function that has made things confusing:

```
# %%
# Define function for printing weights
def print_weights(name, weights):
    first = weights[:, 0] / np.max(np.abs(weights[:, 0]))
    print(name + ': ' + ', '.join(['{:.3f}'.format(item) for item in first]))
```

As you can see, it normalizes the weights for printing purposes and the weights will not match the matlab ones after that.

Here's few example runs without normalization with the current data:

**upenalty 1.0, vpenalty 1.0:**
Corrcoef for comp 1: 0.7629782437780296
X: -0.763, 0.647
Z: -0.756, -0.655

**upenalty 0.9, vpenalty 0.9:**
Corrcoef for comp 1: 0.7504008661808488
X: -0.945, 0.328
Z: -0.945, -0.328

**upenalty 0.8, vpenalty 0.8:**
Corrcoef for comp 1: 0.706432816761567
X: -0.990, 0.141
Z: -0.990, -0.141

**upenalty 0.7, vpenalty 0.7:**
Corrcoef for comp 1: 0.6530956386670856
X: -1.000, 0.000
Z: -1.000, -0.000

Penalizing more (decreasing the upenalty and vpenalty values) makes the correlation coefficient smaller and the canonical weights more sparse. With penalties 0.7 and 0.7, it's already maximally sparse.

I agree there is merit to the simulated data, but the data should be rich enough so that the effect of penalizing is easy to see. Perhaps both would be good!

**Comment by teekuningas** [comment]
Here are similar runs for the earlier simulated data:

**upenalty 0.8, vpenalty 0.8:**
Corrcoef for comp 1: 0.2816370314121776
X: -0.713, -0.649, -0.157, 0.024, -0.063, 0.203
Z: -0.015, -0.578, -0.657, -0.482, 0.046

**upenalty 0.7, vpenalty 0.7:**
Corrcoef for comp 1: 0.2746440818972273
X: -0.747, -0.636, -0.127, 0.000, -0.098, 0.106
Z: -0.000, -0.541, -0.814, -0.210, 0.000

**upenalty 0.6, vpenalty 0.6:**
Corrcoef for comp 1: 0.24886907506597022
X: -0.790, -0.610, -0.011, 0.000, -0.059, 0.000
Z: 0.000, -0.447, -0.894, -0.000, 0.000

**upenalty 0.5, vpenalty 0.5:**
Corrcoef for comp 1: 0.20048623269512908
X: -0.966, -0.259, -0.000, -0.000, -0.000, 0.000
Z: -0.000, -0.126, -0.992, -0.000, 0.000

**upenalty 0.4, vpenalty 0.4:**
Corrcoef for comp 1: 0.1583767679101844
X: -1.000, -0.000, -0.000, -0.000, -0.000, 0.000
Z: -0.000, -0.000, -1.000, -0.000, 0.000

And again, the correlation coefficients go smaller and the canonical weights get more sparse.

**Comment by teekuningas** [comment]
To recap, there was an actual bug with the weight printing function before in the plot_cca.py. It produced nans and infs because of dividing by zero in the normalization. Now in the latest version I pushed just now, the normalization is removed as it was only complicating things.

However, the algorithm itself is intact and should work fine.

Hope to hear your update!

 -- Erkka

**Comment by JohannesWiesner** [comment]
@fabioboh Just out of curiosity, does Erkkas pull request solve your second problem?

> 2- coefficients differ compared to the ones produced by the R implementation (I used the rpy2 package to use it).

**Comment by fabioboh** [comment]
@Teekuningas thanks a lot for the input! @JohannesWiesner  I am busy with other stuff but will answer you in the next days.

**Comment by fabioboh** [comment]
@Teekuningas @JohannesWiesner I now obtain the same coefficients with both implementations!
